export const foodData = [
  {
    id: "1",
    name: "Waffle",
    description: "Waffle with Berries",
    price: 6.5,
    desktop: "/assets/images/image-waffle-desktop.jpg",
    tablet: "/assets/images/image-waffle-tablet.jpg",
    mobile: "/assets/images/image-waffle-mobile.jpg",
    thumbnail: "/assets/images/image-waffle-thumbnail.jpg",
  },
  {
    id: "2",
    name: "Crème Brûlée",
    description: "Vanilla Bean Crème Brùlée",
    price: 7.0,
    desktop: "/assets/images/image-creme-brulee-desktop.jpg",
    tablet: "/assets/images/image-creme-brulee-tablet.jpg",
    mobile: "/assets/images/image-creme-brulee-mobile.jpg",
    thumbnail: "/assets/images/image-creme-brulee-thumbnail.jpg",
  },
  {
    id: "3",
    name: "Macaron",
    description: "Macaron Mix of Five",
    price: 8.0,
    desktop: "/assets/images/image-macaron-desktop.jpg",
    tablet: "/assets/images/image-macaron-tablet.jpg",
    mobile: "/assets/images/image-macaron-mobile.jpg",
    thumbnail: "/assets/images/image-macaron-thumbnail.jpg",
  },
  {
    id: "4",
    name: "Tiramisu",
    description: "Classic Tiramisu",
    price: 5.5,
    desktop: "/assets/images/image-tiramisu-desktop.jpg",
    tablet: "/assets/images/image-tiramisu-tablet.jpg",
    mobile: "/assets/images/image-tiramisu-mobile.jpg",
    thumbnail: "/assets/images/image-tiramisu-thumbnail.jpg",
  },
  {
    id: "5",
    name: "Baklava",
    description: "Pistachio Baklava",
    price: 4.0,
    desktop: "/assets/images/image-baklava-desktop.jpg",
    tablet: "/assets/images/image-baklava-tablet.jpg",
    mobile: "/assets/images/image-baklava-mobile.jpg",
    thumbnail: "/assets/images/image-baklava-thumbnail.jpg",
  },
  {
    id: "6",
    name: "Pie",
    description: "Lemon Meringue Pie",
    price: 5.0,
    desktop: "/assets/images/image-meringue-desktop.jpg",
    tablet: "/assets/images/image-meringue-tablet.jpg",
    mobile: "/assets/images/image-meringue-mobile.jpg",
    thumbnail: "/assets/images/image-meringue-thumbnail.jpg",
  },
  {
    id: "7",
    name: "Cake",
    description: "Red Velvet Cake",
    price: 4.5,
    desktop: "/assets/images/image-cake-desktop.jpg",
    tablet: "/assets/images/image-cake-tablet.jpg",
    mobile: "/assets/images/image-cake-mobile.jpg",
    thumbnail: "/assets/images/image-cake-thumbnail.jpg",
  },
  {
    id: "8",
    name: "Brownie",
    description: "Salted Caramel Brownie",
    price: 4.5,
    desktop: "/assets/images/image-brownie-desktop.jpg",
    tablet: "/assets/images/image-brownie-tablet.jpg",
    mobile: "/assets/images/image-brownie-mobile.jpg",
    thumbnail: "/assets/images/image-brownie-thumbnail.jpg",
  },
  {
    id: "9",
    name: "Panna Cotta",
    description: "Vanilla Panna Cotta",
    price: 6.5,
    desktop: "/assets/images/image-panna-cotta-desktop.jpg",
    tablet: "/assets/images/image-panna-cotta-tablet.jpg",
    mobile: "/assets/images/image-panna-cotta-mobile.jpg",
    thumbnail: "/assets/images/image-panna-cotta-thumbnail.jpg",
  },
];
